/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package pl.xpu

import spock.lang.Specification
import spock.lang.Unroll

class VatVerificatorTest extends Specification {

    @Unroll
    def "verify returns true"() {
        expect:
        VatVerificator.verify("7792488801") == true

//        then:
//        result == expectedResult
//
//        where:
//        nip   || expectedResult
//        null  || false
//        ""    || false
//        "nip" || false
//        "7792488801" || true
    }
}
