/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package pl.xpu

import spock.lang.Specification
import spock.lang.Unroll

class VatVerificatorTest extends Specification {

    @Unroll
    def "verify returns true"() {
        when:
        def result = VatVerificator.verify(nip)

        then:
        result == expectedResult

        where:
        nip   || expectedResult
        null  || false
        ""    || false
        "nip" || false
        "123" || true
    }
}
